upes-open/OSoC-24-Health-Reserve

backend/index.js
backend/models/user.js
backend/package-lock.json
backend/package.json

resolves: #10 #14 
1.Implemented user authentication-login sign up 
2.created user schema name email password.
3.used bcrypt for password encryption related tasks.
4.cookie-parser for cookie session.

Implemented user authentication using JWT and created user Schema

---

frontend/src/App.jsx
frontend/src/components/Home/Home.css

Centered the content box and removed the nav bar.
Also took care of root file path of image in css.

Fixes #27:Create Home Page

---

backend/models/user.js

Worked on Issue #40

---

backend/models/user.js

Worked on #40

---

frontend/src/App.jsx
frontend/src/components/Login-page/Login.jsx

Worked on #45

---

frontend/src/components/Home/Home.css

Issue #45 fixes

---

backend/index.js
backend/models/patient.js

Fixed patient schema

---

frontend/src/App.css
frontend/src/components/Footer/Footer.css
frontend/src/components/Navbar/Navdoctor.css
frontend/src/components/Navbar/Navdoctor.jsx
frontend/src/components/Navbar/Navpatient.jsx
frontend/src/components/Register-page/Register.css
frontend/src/components/Register-page/Register.jsx

Fixed UI of registration page, removed the empty space between form and footer and removed the horizontal scroll #46

Worked on Fixing UI #46

---

frontend/src/components/Register-page/Register.jsx

doctor and patient selector

---

frontend/.gitignore
frontend/src/App.jsx
frontend/src/components/PatientCard/Card.css
frontend/src/components/PatientCard/Card.jsx
frontend/src/components/ViewRecord/ViewRecord.css
frontend/src/components/ViewRecord/ViewRecord.jsx

View Medical Records Page

---

frontend/src/components/Navbar/Navdoctor.css
frontend/src/components/Navbar/Navdoctor.jsx

Improved Navbar

---

frontend/src/components/Register-page/Register.jsx

Improve UX

---

frontend/src/components/PatientCard/Card.css
frontend/src/components/PatientCard/Card.jsx
frontend/src/components/ViewRecord/ViewRecord.css
frontend/src/components/ViewRecord/ViewRecord.jsx
frontend/src/index.css

Improved View Records page

---

backend/index.js

Fixed backend

---

backend/index.js
backend/models/user.js
backend/package-lock.json
backend/package.json

Implemented User Session

---

backend/index.js
backend/models/patient.js
backend/models/user.js
backend/routes/routes.js
frontend/src/components/Login-page/Login.jsx
frontend/src/components/User-Dashboard/userDashboard.jsx

Refactoring done

---

frontend/src/App.css
frontend/src/App.jsx
frontend/src/components/FolderDash/dash.css
frontend/src/components/FolderDash/dash.jsx
frontend/src/components/Home/Home.css
frontend/src/components/Login-page/Login.css
frontend/src/components/Login-page/Login.jsx
frontend/src/components/Navbar/Navdoctor.css
frontend/src/components/User-Dashboard/Dashboard.css
frontend/src/index.css

created dashboard page with UI and redirection to dashboard after successful login

Fixes #87:Create dashboard

---

frontend/src/components/Navbar/Navdoctor.css
frontend/src/components/Navbar/Navdoctor.jsx
frontend/src/components/Navbar/Navpatient.jsx

added profile page redirection

---

backend/models/user.js

Updated User Schema

---

backend/routes/routes.js

Added encryption when saving images

---

frontend/index.html

Changed website logo and name

---

frontend/src/components/Profile Page/profile.css
frontend/src/components/Profile Page/profile.jsx

Fixed Profile Page UI

---

frontend/src/components/Login-page/Login.css
frontend/src/components/Login-page/Login.jsx
frontend/src/components/Register-page/Register.css
frontend/src/components/Register-page/Register.jsx

Fixed login and register page

---

frontend/src/components/Navbar/Navdoctor.jsx

UI Improvement

---

backend/connectDB/connect.js
backend/index.js
backend/package-lock.json
backend/package.json
backend/routes/routes.js

Implemented Express Session

---

backend/index.js
backend/routes/routes.js

Refactored files

---

backend/package.json
backend/pnpm-lock.yaml
frontend/pnpm-lock.yaml
frontend/src/App.jsx
frontend/src/components/Login-page/Login.jsx
frontend/src/components/Navbar/Navdoctor.jsx
frontend/src/components/PatientRecord/PatientRecords.jsx
frontend/src/components/Register-page/Register.css
frontend/src/components/Register-page/Register.jsx
frontend/src/components/User-Dashboard/userDashboard.jsx
frontend/src/components/ViewRecord/ViewRecord.jsx

Fixes #131

---

backend/routes/routes.js
frontend/src/components/Doctor/Doctor.css
frontend/src/components/Doctor/Doctor.jsx
frontend/src/components/Navbar/Navdoctor.jsx

Generated different /doctors for patient and doctor

---

frontend/src/components/Doctor/Doctor.jsx
frontend/src/components/SeePatients/SeePatientCard.jsx

Fixes #149 redirect issue

---

frontend/src/components/Login-page/Login.css
frontend/src/components/Register-page/Register.css
frontend/src/components/Register-page/Register.jsx

Fixed Login and Register Pages

---

frontend/src/components/FolderDash/dash.css
frontend/src/components/FolderDash/dash.jsx

Fixed dashboard

---

backend/routes/routes.js
frontend/src/components/Doctor/Doctor.jsx
frontend/src/components/Navbar/Navdoctor.jsx
frontend/src/components/SeePatients/SeePatientCard.jsx
frontend/src/components/ViewRecord/ViewRecord.css
frontend/src/components/ViewRecord/ViewRecord.jsx

Patient Details

---

frontend/src/components/Navbar/Navdoctor.jsx

Redirection

---

backend/routes/routes.js
frontend/src/components/Profile Page/profile.css
frontend/src/components/Profile Page/profile.jsx

Updated Profile Page

---

backend/index.js
frontend/src/components/PatientRecord/PatientRecords.jsx
frontend/src/components/User-Dashboard/userDashboard.jsx
frontend/src/components/ViewRecord/ViewRecord.css
frontend/src/components/ViewRecord/ViewRecord.jsx

UI/UX Functionality
